Check account balances before we allow money transfers #183691063
Technical-Enablement-PingIdentity/BXFinance-Apps pull request #193
Opened 2022-12-08 22:05 UTC by ericanderson91

2022-12-08 23:29 UTC, michaelsanchez-pingidentity requested changes
Good stuff. Just one catch on leftover logging.

2022-12-08 23:29 UTC, michaelsanchez-pingidentity commented on bxfinance/src/pages/pay-transfer/accounts-transfer.js
> +        console.log(fromAccount, +this.state.xfrAmount);
make sure to remove all console.logs before we push. or any other troubleshooting code.

2022-12-09 15:24 UTC, ericanderson91 commented on bxfinance/src/pages/pay-transfer/accounts-transfer.js
> +        console.log(fromAccount, +this.state.xfrAmount);
Good catch

2022-12-09 15:54 UTC, michaelsanchez-pingidentity approved these changes
Reviewed.

2022-12-09 15:55 UTC, merged